LEFT = 1
RIGHT = 2
UP = 4
DOWN = 8

LEFT_RIGHT = LEFT + RIGHT
LEFT_UP = LEFT + UP
LEFT_DOWN = LEFT + DOWN
RIGHT_UP = RIGHT + UP
RIGHT_DOWN = RIGHT + DOWN
UP_DOWN = UP + DOWN

LEFT_RIGHT_UP = LEFT + RIGHT + UP
LEFT_RIGHT_DOWN = LEFT + RIGHT + DOWN
LEFT_UP_DOWN = LEFT + UP + DOWN
RIGHT_UP_DOWN = RIGHT + UP + DOWN

LEFT_RIGHT_UP_DOWN = LEFT + RIGHT + UP + DOWN

DIRECTIONS = (LEFT, RIGHT, UP, DOWN)
CORNERS = (LEFT_UP, LEFT_DOWN, RIGHT_UP, RIGHT_DOWN)
